stages:
  ingest_interactions:
    cmd: python scripts/Ingestion/userinteraction_batch_ingestion.py
    deps:
    - data/source/user_interactions
    - scripts/Ingestion/userinteraction_batch_ingestion.py
    outs:
    - data/raw/batch/user_interactions

  ingest_profiles:
    cmd: python scripts/Ingestion/user_profiles_batch_ingestion.py
    deps:
    - data/source/user_profiles
    - scripts/Ingestion/user_profiles_batch_ingestion.py
    outs:
    - data/raw/batch/user_profiles

  ingest_products:
    cmd: python scripts/Ingestion/ingest_product.py
    deps:
    - scripts/Ingestion/ingest_product.py
    outs:
    - data/raw/api

  validate:
    cmd: python scripts/validation/validation_script.py
    deps:
    - data/raw
    - scripts/validation/validation_script.py
    metrics:
    - data/quality_reports

  curate:
    cmd: python scripts/curation/curate_data.py
    deps:
    - data/raw
    - scripts/curation/curate_data.py
    - data/quality_reports
    outs:
    - data/curated
    metrics:
    - metrics/curation_metadata.json

  feature_engineering:
    cmd: python scripts/feature_eng/main.py --incremental
    deps:
    - data/curated
    - scripts/feature_eng/main.py
    - scripts/feature_eng/metastore.py
    - scripts/feature_eng/config.py
    - scripts/feature_eng/transformers.py
    outs:
    - data/processed/features/retailx_features.db:
        persist: true