import mlflow
import pandas as pd
from pathlib import Path
from datetime import datetime

# Configuration
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
MLRUNS_DIR = PROJECT_ROOT / "mlruns"
REPORT_PATH = PROJECT_ROOT / "docs" / "model_performance_report.md"

# Setup MLflow
mlflow.set_tracking_uri(f"sqlite:///{str(PROJECT_ROOT / 'mlflow.db')}")
EXPERIMENT_NAME = "RecoMart_Experiments"

def generate_report():
    print(f"Connecting to MLflow at {mlflow.get_tracking_uri()}...")
    
    # Get Experiment
    experiment = mlflow.get_experiment_by_name(EXPERIMENT_NAME)
    if not experiment:
        print(f"Experiment '{EXPERIMENT_NAME}' not found.")
        return

    # Get Runs
    runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
    
    # Filter for successful runs
    successful_runs = runs[runs['status'] == 'FINISHED']
    
    if successful_runs.empty:
        print("No successful runs found.")
        return

    # Get the latest run
    latest_run = successful_runs.sort_values("start_time", ascending=False).iloc[0]
    
    # Extract all parameters dynamically
    params = {k.replace('params.', ''): v for k, v in latest_run.items() if k.startswith('params.') and pd.notna(v)}
    params_table = "\n".join([f"| `{k}` | {v} |" for k, v in params.items()])
    if not params_table:
        params_table = "| No Parameters Logged | - |"
    
    # Start Building Markdown
    md_content = f"""# RecoMart Model Performance Report
**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Experiment:** {EXPERIMENT_NAME}

## 1. Executive Summary
This report summarizes the performance of the latest trained Recommendation Models.
Authentication and tracking provided by **MLflow**.

- **Latest Run ID:** `{latest_run.run_id}`
- **Training Date:** {latest_run.start_time}

## 2. Model Methodology & Performance

### Collaborative Filtering (SVD)
**What it is:** Collaborative filtering makes recommendations based on the collective behavior of all users. It assumes that if User A and User B have similar tastes in the past, they will likely agree on items in the future.

**How it is trained:** We use **Singular Value Decomposition (SVD)**, a matrix factorization technique.
1. We create a large matrix where rows are users and columns are products.
2. The matrix is populated with "implicit scores" (e.g., how many times a user clicked or bought an item).
3. SVD decomposes this matrix into "latent factors"—hidden features that capture the essence of a user's style or a product's appeal.
4. Recommendations are generated by calculating the dot product between these user and item factors.

| Metric | Value | Description |
| :--- | :--- | :--- |
| **Test RMSE** | **{f"{latest_run.get('metrics.svd_test_rmse'):.4f}" if pd.notna(latest_run.get('metrics.svd_test_rmse')) else 'N/A'}** | Root Mean Squared Error. Measures the average deviation between predicted and actual scores. |
| Explained Variance | {f"{latest_run.get('metrics.svd_explained_variance'):.4f}" if pd.notna(latest_run.get('metrics.svd_explained_variance')) else 'N/A'} | Indicates how much of the data's complexity is captured by the latent factors. |

### Content-Based Filtering
**What it is:** Unlike collaborative filtering, this model focuses on the **properties** of the items themselves (category, brand, price, rating). It recommends items that are similar to what the specific user has interacted with in the past.

**How it is trained:**
1. **Feature Engineering:** We convert product attributes (e.g., "Electronics", "Sony") into numerical vectors using one-hot encoding and scaling.
2. **User Profiling:** For each user, we calculate a "User Profile" by taking the weighted average of the vectors of all products they have liked.
3. **Similarity Matching:** To recommend, we compare the User Profile against the entire product catalog using **Cosine Similarity**.
4. The items with the highest similarity scores to the user's historical profile are recommended.

| Metric | Value | Description |
| :--- | :--- | :--- |
| **Precision@50** | **{f"{latest_run.get('metrics.content_precision_50'):.4f}" if pd.notna(latest_run.get('metrics.content_precision_50')) else 'N/A'}** | Fraction of top-50 recommendations that were actually in the user's test set. |
| **Recall@50** | **{f"{latest_run.get('metrics.content_recall_50'):.4f}" if pd.notna(latest_run.get('metrics.content_recall_50')) else 'N/A'}** | Percentage of the user's actual test items that were caught in the top-50 list. |
| **Hit Rate@50** | **{f"{latest_run.get('metrics.content_hit_rate_50'):.4f}" if pd.notna(latest_run.get('metrics.content_hit_rate_50')) else 'N/A'}** | Percentage of users who received at least one relevant recommendation. |
| Avg Confidence | {f"{latest_run.get('metrics.content_avg_confidence'):.4f}" if pd.notna(latest_run.get('metrics.content_avg_confidence')) else 'N/A'} | The average cosine similarity score for the top recommendations. |



## 3. Training Metadata
Metadata allows for full reproducibility of this training run.

### All Parameters Tracked
| Parameter | Value |
| :--- | :--- |
{params_table}

---
*Report automatically generated from MLflow tracking database.*
"""

    # Write to file
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        f.write(md_content)
    
    print(f"Report successfully generated at: {REPORT_PATH}")
    print("\nPreview of Report Content:")
    print("-" * 30)
    print(md_content[:500] + "...")

if __name__ == "__main__":
    generate_report()
